services:
  web:
    build: .
    container_name: django_app
    working_dir: /app
    command: >
      sh -c "
        while ! nc -z db 3306; do
          echo 'Waiting for MySQL...';
          sleep 2;
        done;
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings

    depends_on:
      - db

  db:
    image: ilwad/my-mysql-with-new-data:final1
    container_name: mysql_db
    ports:
      - "3302:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: DESD1 



